Traceback (most recent call last):
  File "<ipython-input-5-c01f09b0e0c8>", line 2, in <cell line: 1>
    raise Exception('This is the error message.')
Exception: This is the error message.
